//---BENEFITS
const SET_NP_BEN_SEL = 'SET_NP_BEN_SEL';
const ADD_NP_BEN = 'ADD_NP_BEN';
const SEND_NP_FORM = 'SEND_NP_FORM';
//---PLANS
const GET_PLANS_BENEFITS = 'GET_PLANS_BENEFITS';
const GET_BENEFITS = 'GET_BENEFITS';
//-----SPECIALITIES------
const GET_SPECIALITIES = 'GET_SPECIALITIES';
const FIND_SPECIALITY = 'FIND_SPECIALITY';
const DELETE_SPECIALITY = 'DELETE_SPECIALITY';
//-----AFFILIATES------
const GET_AFFILIATES = 'GET_AFFILIATES';
//------FORM REG 1
const GET_STATES = 'GET_STATES';
const GET_LOCALITIES = 'GET_LOCALITIES';
//--------USERS------------------------
const GET_USERS = 'GET_USERS';
//--------GUEST------------------------
const GET_REF_CONTACT = 'GET_REF_CONTACT';

export {
    SET_NP_BEN_SEL,
    ADD_NP_BEN,
    SEND_NP_FORM,
    GET_PLANS_BENEFITS,
    GET_BENEFITS,
    GET_SPECIALITIES,
    FIND_SPECIALITY,
    DELETE_SPECIALITY,
    GET_AFFILIATES,
    GET_STATES,
    GET_LOCALITIES,
    GET_USERS,
    GET_REF_CONTACT,
};
