//---BENEFITS
const SET_NP_BEN_SEL = 'SET_NP_BEN_SEL';
const ADD_NP_BEN = 'ADD_NP_BEN';
const SEND_NP_FORM = 'SEND_NP_FORM';
//---PLANS
const GET_PLANS_BENEFITS = "GET_PLANS_BENEFITS";
const GET_BENEFITS = "GET_BENEFITS";
//-----SPECIALITIES------
const GET_SPECIALITIES = "GET_SPECIALITIES";
const FIND_SPECIALITY = 'FIND_SPECIALITY';
const DELETE_SPECIALITY = 'DELETE_SPECIALITY';

export { 
    SET_NP_BEN_SEL,
    ADD_NP_BEN,
    SEND_NP_FORM,
    GET_PLANS_BENEFITS,
    GET_BENEFITS,
    GET_SPECIALITIES,
    FIND_SPECIALITY,
    DELETE_SPECIALITY
    };
